[theme]
primaryColor = "#00d4ff"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"
EMAIL_USER = "siveshversion@gmail.com"
EMAIL_PASS = "sivesh@G00gle"

